### ISSUE TITLE
adjust NERC vocabulary choice for heterotrophic bacteria

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-attune-fcm-discrete-transect#3]
Email from Emily 2023-03-28: 
for column header definition initially selected http://vocab.nerc.ac.uk/collection/F02/current/F0200010/ however they are actually an aggregate of both high and low nucleic acid

**Comment by ecrockford** [comment]
Should be aggregate of
http://vocab.nerc.ac.uk/collection/F02/current/F0200010/
http://vocab.nerc.ac.uk/collection/F02/current/F0200011/

Because they are actually an aggregate of both high and low nucleic acid. Currently Emily doesn’t gate to separate high from low, so it is just “all”

See definition options here:
http://vocab.nerc.ac.uk/collection/F02/current/

Unfortunately the combo options of (http://vocab.nerc.ac.uk/collection/F02/current/F0200009/) is labeled as deprecated

**Comment by sbeaulieu** [comment]
include both NERC vocabulary term identifiers in the attributeDefinition for hetprok_cells_per_ml (in -info.xlsx)
see the attributeDefinition for redeuk_leq_20um_cells_per_ml for an example of how we are inclusive of two NERC vocabulary terms

**Comment by ecrockford** [comment]
Edited hetprok_cells_per_ml to say "abundance per unit volume of heterotrophic bacterial cells including http://vocab.nerc.ac.uk/collection/F02/current/F0200010/ and http://vocab.nerc.ac.uk/collection/F02/current/F0200011/"
